# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'


target 'RxSwift_Playground' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift_Playground
  pod 'RxSwift'
  pod 'RxCocoa'

end