source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'UIKitCustomView' do
  pod 'SnapKit', '~> 5.6.0'
end
