platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'RxSwiftTestPatterns' do
  use_frameworks!

  inhibit_all_warnings!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'

  target 'RxSwiftTestPatternsTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'RxTest'
    pod 'RxBlocking'
    pod 'Mockingjay'
  end

end
