# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

# platform :ios do
#    desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#   end
# end

desc 'Build iOS application'
lane :beta do
  build_app(
    scheme: "FastlaneAPP",
    xcargs: "-allowProvisioningUpdates",
    output_directory: 'build',
    codesigning_identity:"iOS Developer",
    export_options: {
      method: "development",
      provisioningProfiles: { 
        "Swift-Beginners.FastlaneAPP" => "FastlaneAPP_iOS_Development"
      }
    } 
 )
end

desc 'Upload to firebase app distribution'
lane :deploy_firebase do
   firebase_app_distribution(
     app: "1:337216137543:ios:864e8ec127962e86544462",
     firebase_cli_token: "1//0en3fntUvNS8OCgYIARAAGA4SNwF-L9IreZ9ixnelwKmACoI-11j7Y62D_jTYNuttrgq7jg8QC8x3SkpFZ1cpVVA5Lga43DNT4Ww",
     groups: "tctester",
     ipa_path: "build/FastlaneAPP.ipa",
     release_notes: "Text of release notes"
)
end
