# この指定がないとpod instalでエラーになる
source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftUIRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIRxSwift
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

end
